import { User, Car, Client, Rental, Payment, Invoice, Document, ActivityLog, Incident, Maintenance, Notification, Assistance, InsuranceCompany, InsuranceLog, VehicleInstallment, InstallmentPayment, Expense, FinancialLog } from "../../types.js";
import bcrypt from "bcryptjs";

// Initial Mock Data
export const db = {
  users: [
    {
      id: 1,
      name: "Admin BMS",
      email: "admin@bms.ma",
      password: bcrypt.hashSync("admin123", 10),
      role: "admin" as const,
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: "Agent Kamal",
      email: "agent@bms.ma",
      password: bcrypt.hashSync("agent123", 10),
      role: "agent" as const,
      createdAt: new Date().toISOString(),
    },
  ] as User[],
  cars: [
    {
      id: 1,
      brand: "Range Rover",
      model: "Sport",
      year: 2023,
      licensePlate: "12345-A-7",
      color: "Noir",
      pricePerDay: 1500,
      status: "available",
      mileage: 15000,
      fuelType: "diesel",
      transmission: "automatic",
      imageUrl: "https://picsum.photos/seed/rr/800/600",
      insuranceExpiry: "2025-06-01",
      registrationExpiry: "2025-12-01",
      inspectionExpiry: "2025-03-01",
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      brand: "Mercedes",
      model: "Classe G",
      year: 2022,
      licensePlate: "98765-B-6",
      color: "Gris",
      pricePerDay: 2500,
      status: "available",
      mileage: 8000,
      fuelType: "gasoline",
      transmission: "automatic",
      imageUrl: "https://picsum.photos/seed/gclass/800/600",
      insuranceExpiry: "2025-08-15",
      registrationExpiry: "2025-11-20",
      inspectionExpiry: "2025-05-10",
      createdAt: new Date().toISOString(),
    },
  ] as Car[],
  clients: [
    {
      id: 1,
      fullName: "Ahmed Alami",
      phone: "0661234567",
      email: "ahmed@gmail.com",
      address: "Casablanca, Maarif",
      licenseNumber: "AB123456",
      licenseExpiration: "2028-12-31",
      notes: "Client fidèle",
      createdAt: new Date().toISOString(),
    }
  ] as Client[],
  rentals: [] as Rental[],
  payments: [] as Payment[],
  invoices: [] as Invoice[],
  documents: [] as Document[],
  activityLogs: [] as ActivityLog[],
  incidents: [] as Incident[],
  maintenances: [] as Maintenance[],
  notifications: [] as Notification[],
  assistances: [] as Assistance[],
  insuranceCompanies: [
    {
      id: 1,
      name: "AXA Assurance",
      contactPerson: "M. Benjelloun",
      phone: "0522123456",
      email: "contact@axa.ma",
      status: "active",
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: "Saham Assurance",
      contactPerson: "Mme. Tazi",
      phone: "0522987654",
      email: "support@saham.ma",
      status: "active",
      createdAt: new Date().toISOString(),
    }
  ] as InsuranceCompany[],
  insuranceLogs: [] as InsuranceLog[],
  vehicleInstallments: [] as VehicleInstallment[],
  installmentPayments: [] as InstallmentPayment[],
  expenses: [] as Expense[],
  financialLogs: [] as FinancialLog[],
};
